import { Metadata } from 'next';
import HomeContent from '@/parts/home-content';

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

const Home = () => {
  return <>
    <button id='roll' style={{zIndex: -2, position: 'absolute', opacity: 0}}></button>
    <HomeContent/>
  </>
}

export default Home;