import { Metadata } from 'next';
import HomeContent from '@/parts/home-content';

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

const Home = () => {
  return <HomeContent/>
}

export default Home;